# Generated by Django 5.0 on 2024-01-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_volunteer',
            name='availability',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_volunteer',
            name='blood_group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_volunteer',
            name='emergency_contect',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
