# Generated by Django 5.0 on 2024-01-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis_app', '0002_tbl_volunteer_availability_tbl_volunteer_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_disaster_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('hospitalized_count', models.IntegerField(max_length=100, null=True)),
                ('death_count', models.IntegerField(max_length=100, null=True)),
            ],
        ),
    ]
