# Generated by Django 5.0 on 2024-01-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis_app', '0004_tbl_earthquake_tbl_flood_tbl_hurricane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_flood',
            old_name='infrstructure_damage',
            new_name='infrastructure_damage',
        ),
        migrations.RemoveField(
            model_name='tbl_earthquake',
            name='aftershoks',
        ),
        migrations.AddField(
            model_name='tbl_earthquake',
            name='aftershocks',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
