# Generated by Django 5.0 on 2024-01-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis_app', '0005_rename_infrstructure_damage_tbl_flood_infrastructure_damage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_disaster_manage',
        ),
        migrations.AlterField(
            model_name='tbl_flood',
            name='evacuations_rescues',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_flood',
            name='update_change',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
