# Generated by Django 5.0 on 2024-02-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis_app', '0006_delete_tbl_disaster_manage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('mobile', models.IntegerField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
