# Generated by Django 5.0 on 2024-02-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis_app', '0010_rename_password_tbl_incident_incident_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('contect_detail', models.IntegerField(max_length=100, null=True)),
                ('capacity', models.IntegerField(max_length=100, null=True)),
                ('fecility', models.CharField(max_length=100, null=True)),
                ('volunteer_available', models.IntegerField(max_length=100, null=True)),
            ],
        ),
    ]
