# Generated by Django 5.0 on 2024-02-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis_app', '0012_tbl_shelter_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('feedback', models.CharField(max_length=100, null=True)),
                ('experience', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_shelter_view',
        ),
    ]
