# Generated by Django 5.0 on 2024-02-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crisis_app', '0013_tbl_feedback_view_delete_tbl_shelter_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_feedback_view',
            name='experience',
        ),
    ]
