# Generated by Django 4.1.5 on 2024-04-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crisis_app', '0014_remove_tbl_feedback_view_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_feedback_view',
            old_name='email',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback_view',
            name='name',
        ),
        migrations.AddField(
            model_name='tbl_feedback_view',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crisis_app.tbl_user_registration'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('from_me', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crisis_app.tbl_user_registration')),
            ],
        ),
    ]
