from django.urls import path
from . import views
urlpatterns=[
    path('',views.index),
    path('Admin_login/', views.Admin_login),
    path('Admin_login_check/',views.Admin_login_check),
    path('Admin_home/',views.Admin_home),
    path('add_volunteer/',views.add_volunteer),
    path('save_volunteer/',views.save_volunteer),
    path('view_volunteer',views.view_volunteer),
    path('add_disaster_manage/',views.add_disaster_manage),
    path('save_disaster_manage/',views.save_disaster_manage),
    path('view_disaster_manage/',views.view_disaster_manage),
    path('delete_flood/', views.delete_flood),
    path('edit_flood/', views.edit_flood),
    path('add_earthquake/',views.add_earthquake),
    path('save_earthquake/',views.save_earthquake),
    path('view_earthquake/',views.view_earthquake),
    path('add_hurricane/',views.add_hurricane),
    path('save_hurricane/',views.save_hurricane),
    path('view_hurricane/',views.view_hurricane),
    path('add_flood/',views.add_flood),
    path('save_flood/',views.save_flood),
    path('view_flood/',views.view_flood),
    path('user_login/', views.user_login),
    path('user_login_check/',views.user_login_check),
    path('user_registration/',views.user_registration),
    path('save_user_registration/',views.save_user_registration),
    path('view_user_registration/',views.view_user_registration),
    path('user_home/',views.user_home),
    path('add_incident/',views.add_incident),
    path('save_incident/',views.save_incident),
    path('add_shelter/',views.add_shelter),
    path('save_shelter/',views.save_shelter),
    path('view_shelter/',views.view_shelter),
    path('shelter_view/',views.shelter_view),
    path('incident_view/',views.incident_view),
    path('volunteer_view/',views.volunteer_view),
    path('add_feedback/',views.add_feedback),
    path('save_feedback/',views.save_feedback),
    path('feedback_view/', views.feedback_view),
    path('delete_volunteer/',views.delete_volunteer),
    path('edit_volunteer/',views.edit_volunteer),
    path('delete_hurricane/', views.delete_hurricane),
    path('edit_hurricane/', views.edit_hurricane),
    path('delete_earthquake/', views.delete_earthquake),
    path('edit_earthquake/', views.edit_earthquake),
    path('delete_shelter/', views.delete_shelter),
    path('edit_shelter/', views.edit_shelter),
    path('delete_incident/', views.delete_incident),
    path('edit_incident/', views.edit_incident),
    path("hide_feedback/<id>",views.hide_feedback),
    path('contact/',views.contact),
    path('portfolio/', views.portfolio),
    path('safety/', views.safety),
    path("chat/",views.chat),
path('get_messages/', views.get_messages, name='get_messages'),
    path('send_message/', views.save_message, name='send_message'),
    path("admin_chats/",views.admin_chats,name="admin_chats"),
    path("view_user_chat/<id>",views.view_user_chat,name="view_user_chat"),
path('send_message1/', views.save_message1, name='send_message1'),


]